/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_eclipse_actf_util_win32_comclutch_impl_IServiceProviderImpl */

#ifndef _Included_org_eclipse_actf_util_win32_comclutch_impl_IServiceProviderImpl
#define _Included_org_eclipse_actf_util_win32_comclutch_impl_IServiceProviderImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_eclipse_actf_util_win32_comclutch_impl_IServiceProviderImpl
 * Method:    _QueryService
 * Signature: (JJJJJ)Lorg/eclipse/actf/util/win32/comclutch/IUnknown;
 */
JNIEXPORT jobject JNICALL Java_org_eclipse_actf_util_win32_comclutch_impl_IServiceProviderImpl__1QueryService
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
